site_name: Fiware-Orion
site_url: https://telefonicaid.github.io/fiware-orion/doc
repo_url: https://github.com/telefonicaid/fiware-orion.git
site_description: Orion Context Broker
docs_dir: doc/manuals
site_dir: html
markdown_extensions: [toc,fenced_code]
use_directory_urls: false
theme: readthedocs
extra_css: ["http://fiware.org/fiware.css"]
pages:
  - Home: index.md
  - 'Getting Started': 'quick_start_guide.md'
  - 'User & Programmer Guide':
      - Introduction: 'user/index.md'
      - API Walthrough: 'user/walkthrough_apiv1.md'
      - 'Adding entities and attributes': 'user/append_and_delete.md'
      - 'Attribute Metadata': 'user/metadata.md'
      - 'Empty Types': 'user/empty_types.md'
      - 'Structured values for attributes': 'user/structured_attribute_valued.md'
      - Filtering: 'user/filtering.md'
      - Pagination: 'user/pagination.md'
      - Geolocation: 'user/geolocation.md'
      - 'Context Providers': 'user/context_providers.md'
      - 'Updating Registrations and Subscriptions': 'user/updating_regs_and_subs.md'
      - 'Multi tenancy': 'user/multitenancy.md'
      - 'Entity service paths': 'user/service_path.md'
      - 'Context Broker federation': 'user/federation.md'
      - 'Duration (for registrations and subscriptions)': 'user/duration.md'
      - 'Mixing standard and convenience operations': 'user/std_conv_mix.md'
      - 'HTTP and NGSI response codes': 'user/http_and_ngsi_sc.md'
      - 'Security considerations': 'user/security.md'
      - 'Known limitations': 'user/known_limitations.md'
      - 'Forbidden characters': 'user/forbidden_characters.md'
      - Docker: 'user/docker.md'
  - 'Admin Guide':
      - 'Introduction': 'admin/index.md'
      - 'Building from Sources': 'admin/build_source.md'
      - 'Running Orion from command line': 'admin/cli.md'
      - 'Database administration': 'admin/database_admin.md'
      - 'Data model': 'admin/database_model.md'
      - 'Logs': 'admin/logs.md'
      - 'Watchdog': 'admin/watchdog.md'
      - 'Diagnosis': 'admin/diagnosis.md'
      - 'Rush relayer': 'admin/rush.md'
      - 'Management REST interface': 'admin/management_api.md'
      - 'Resources & I/O flows': 'admin/resources.md'
      - 'Upgrading from previous to 0.14.1': 'admin/upgrading_crossing_0-14-1.md'
      - 'Upgrading from previous to 0.19.0': 'admin/upgrading_crossing_0-19-0.md'
      - 'Upgrading from previous to 0.21.0': 'admin/upgrading_crossing_0-21-0.md'